# Generated by Django 4.1.6 on 2023-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('House_no', models.CharField(max_length=100)),
                ('block_no', models.CharField(max_length=100)),
                ('no_of_members', models.CharField(max_length=100)),
                ('picture_of_owner', models.FileField(default='sad.jpg', upload_to='profile.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='SocietySecretory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('picture', models.FileField(default='sad.jpg', upload_to='secretory.jpg')),
            ],
        ),
    ]
