# Generated by Django 4.2.1 on 2023-05-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digitalapp', '0002_events_notice_watchmen_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchmen',
        ),
    ]
