# Generated by Django 4.2.1 on 2023-05-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitalapp', '0003_delete_watchmen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchmen_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('watchman_picture', models.FileField(default='sad.jpg', upload_to='watchman.jpg')),
            ],
        ),
    ]
